version: 0.0
os: linux
files:
  - source: chatapplication
    destination: /home/ubuntu/
  - source: venv
    destination: /home/ubuntu/
hooks:
  BeforeInstall:
    - location: Depend.sh
      timeout: 300
  AfterInstall:
    - location: Envhandle.sh
      timeout: 400
    - location: Appautomate.sh
      timeout: 300
