version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: install_dependancies 
      timeout: 300
  AfterInstall:
    - location: env
      timeout: 300
    - location: automate
      timeout: 300
