version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: Depend.sh
      timeout: 300
  AfterInstall:
    - location: Envhandle.sh
      timeout: 300
    - location: Appautomate.sh
      timeout: 300
